@startuml PackageDiagramOptimized
skinparam packageStyle rectangle
left to right direction

' --- PRESENTATION ---
package "Presentation" {
  class PropertyAPI
  class RoomAPI
  class MediaAPI
  class SearchAPI
  class AuthAPI
}

' --- SERVICE ---
package "Service" {
  class PropertyService
  class RoomService
  class MediaService
  class AuthService
  class SearchService
}

' --- DOMAIN ---
package "Domain" {

  package "Entities" {
    class Property
    class Room
    class Media
    interface IAmenity
    class RoomAmenity
    class PropertyAmenity
  }



}

package "RepositoryInfra" {

  package "Repositories" {
    class PropertyRepositoryImpl
    class RoomRepositoryImpl
    class MediaRepositoryImpl
    interface IPropertyRepository
    interface IRoomRepository
    interface IMediaRepository
  }
  package "Adapters" {
    class S3MediaStorage
    class AWSCognitoAuthProvider
    interface IMediaStorage

    class AWSCognitoAuthProvider
    interface IAuthProvider

  }


}

"Presentation" ..> "Service"
"Service" ..> "Domain"
"Service" ..> "RepositoryInfra"


IPropertyRepository <|.. PropertyRepositoryImpl
IRoomRepository <|.. RoomRepositoryImpl
IMediaRepository <|.. MediaRepositoryImpl
IMediaStorage <|.. S3MediaStorage
IAuthProvider <|.. AWSCognitoAuthProvider

'iamenity
IAmenity <|.. RoomAmenity
IAmenity <|.. PropertyAmenity



@enduml
