@startuml sequence_search_strict
skinparam style strictuml
skinparam sequenceMessageAlign center

actor User
participant Property as Prop
participant Room as R
participant Media as M


User -> Prop: searchProperties(criteria)
activate Prop

loop For each property in results
    Prop -> R: getRoomDetails()
    activate R
    R --> Prop: roomDetails
    deactivate R

    Prop -> M: getPropertyMedia()
    activate M
    M --> Prop: mediaDetails
    deactivate M

    Prop --> User: propertyDetails
end

deactivate Prop
@enduml