@startuml sequence_delete_property_final
skinparam style strictuml
skinparam sequenceMessageAlign center

actor PropertyOwner as Owner
participant Property as Prop
participant Room as R
participant Media as M
participant PropertyAmenity as PA
participant RoomAmenity as RA

' --- Delete Property triggered by Owner ---
Owner -> Prop: deleteProperty()
activate Prop

' --- Delete Property Amenities ---
loop For each property amenity
    Prop -> PA: deleteAmenity()
    activate PA
    PA --> Prop: deleted
    deactivate PA
end

' --- Delete Property Media ---
loop For each media of property
    Prop -> M: deletePropertyMedia()
    activate M
    M --> Prop: deleted
    deactivate M
end

' --- Delete Rooms ---
loop For each room of property
    Prop -> R: deleteRoom()
    activate R

    ' Delete Room Amenities
    loop For each room amenity
        R -> RA: deleteAmenity()
        activate RA
        RA --> R: deleted
        deactivate RA
    end

    ' Delete Room Media
    loop For each media of room
        R -> M: deleteRoomMedia()
        activate M
        M --> R: deleted
        deactivate M
    end

    R --> Prop: roomDeleted
    deactivate R
end

' --- Finalize ---
Prop --> Owner: propertyDeleted
deactivate Prop
@enduml
